export const LOCAL_STORAGE_KEYS = {
  GAME: "game-state",
  GAME_STATUS: "game-status",
  PLAYER_NAME: "player-name",
  INPUTED_PLAYER_NAME: "inputed-player-name",
  ACTIVE_PAGE_ID: "active-page-id",
  CURRENT_LANG: "current-lang",
  CURRENT_GAME_MODE: "current-game-mode",
  GREETINGS_SHOWED: "greetings-showed",
  PLAYING_CARDS: "playing-cards",
  DECK: "deck",
  STOCKS: "stocks",
  WASTES: "wastes",
  FOUNDATIONS: "foundations",
  TABLEAUS: "tableaus",
  FIELD: "field",
  ACTIVE_FACES_ID: "active_faces-id",
  ACTIVE_BACKES_ID: "active_backes-id",
};
