import { APPEARANCES_TYPES } from "./AppearancesConfigs";

export const SHOP_SLICE_NAME = "shop";
export const shopBalanceIcon = "🪙";
export const SHOP_STORAGE_KEYS = {
  SHOP: "shop",
};

export const SHOP_CATEGORY = {
  FACES: APPEARANCES_TYPES.FACES,
  SHIRTS: APPEARANCES_TYPES.SHIRTS,
  FONS: APPEARANCES_TYPES.FONS,
};

export const shop_faces_items_ids = {
  faceClassicId: "start_classic_faces",
  faceOldClassicId: "old_classic_faces",
};

export const shop_shirts_items_ids = {
  shirtClassicId: "start_classic_back_img",
  shirtClassic2Id: "classic_back_img2",
  shirtClassic3Id: "classic_back_img3",
  shirtClassic4Id: "classic_back_img4",
  shirtClassic5Id: "classic_back_img5",
  shirtClassic6Id: "classic_back",
  shirtClassic7Id: "dice_back",
  shirtClassic8Id: "goldV_back",
  shirtClassic9Id: "treeB_back",
  shirtClassic10Id: "elegantRed_back",
  shirtClassic11Id: "elegantBlue_back",
};

export const shop_fons_items_ids = {
  fonGreenClassicId: "green_classic_fon",
  fonGreenClassicImgId: "green_classic_fon_img",
  fonClassicId: "classic_fon2",
  fonRedTreeId: "red_tree_fon",
  fonIceId: "ice_fon",
  fonSeaId: "sea_fon",
  fonAquarium2Id: "aquarium2_fon",
  fonNature1Id: "nature1_fon",
  fonLightGreenId: "light_green_fon",
  fonClassic2Id: "classic_fon_2",
  fonClassic3Id: "classic_fon_3",
  fonClassic4Id: "classic_fon_4",
  fonClassic5Id: "classic_fon_5",
  fonClassic6Id: "classic_fon_6",
  fonClassic7Id: "classic_fon_7",
};

export const SHOP_DEFAULT_STATE = {
  activeCategoryId: SHOP_CATEGORY.FACES,
  balance: 1000,
};

export const shop_items_ids = {
  ...shop_faces_items_ids,
  ...shop_shirts_items_ids,
  ...shop_fons_items_ids,
};

export const shop_faces_items = [
  {
    id: shop_faces_items_ids.faceClassicId,
    name: "Классические2",
    type: "faces",
    bgType: "images",
    category: "cardFace",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "start-classic-faces",
    description: "Стандартный дизайн карт",
    rarity: "common",
    unlockCondition: null,
    previewImage: {
      spriteSheet: true,
      img: "./src/assets/cardsImages/classic_cards_mini.png",
      joker: "./src/assets/cardsImages/classic_cards_joker_mini.png",
      manyLines: 4,
      manyColumns: 13,
      styles: {
        borderRadius: "0.5vw",
        padding: "0",
      },
      shopStyles: {
        borderRadius: "0.5vw",
        padding: "0",
      },
    },
  },
  {
    id: shop_faces_items_ids.faceOldClassicId,
    name: "Классические2",
    type: "faces",
    bgType: "images",
    category: "cardFace",
    owned: false,
    isBought: false,
    price: 100,
    styleClass: "old-classic-faces",
    description: "Стандартный дизайн карт",
    rarity: "common",
    unlockCondition: null,
    previewImage: {
      spriteSheet: true,
      img: "./src/assets/cardsImages/old_cards_2_mini.png",
      joker: "./src/assets/cardsImages/old_cards_2_joker_mini.png",
      manyLines: 4,
      manyColumns: 13,
      styles: {
        borderRadius: "0.5vw",
        padding: "0",
      },
      shopStyles: {
        borderRadius: "0.5vw",
        padding: "0",
      },
    },
  },
];

export const shop_shirts_items = [
  {
    id: shop_shirts_items_ids.shirtClassicId,
    name: "Классическая рубашка",
    type: "backs",
    bgType: "images",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "start-classic-back-img",
    description: "Классическая рубашка",
    rarity: "common",
    unlockCondition: null,
    previewImage: {
      spriteSheet: false,
      img: "./src/assets/cardsImages/shirt1.png",
      manyLines: 1,
      manyColumns: 4,
      bgPositionX: 0,
      bgPositionY: 0,
      styles: {
        borderRadius: "1.5vw",
        padding: "0",
      },
      shopStyles: {
        borderRadius: "1.5vw",
        padding: "0",
        // backgroundSize: "contain",
        backgroundSize: "cover",
        backgroundPosition: "center",
      },
    },
  },
  {
    id: shop_shirts_items_ids.shirtClassic2Id,
    name: "Классическая рубашка",
    type: "backs",
    bgType: "images",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "classic-back",
    description: "Классическая рубашка",
    rarity: "common",
    unlockCondition: null,
    // previewImage: "assets/shop/previews/blue_back.png",
    previewImage: {
      spriteSheet: false,
      img: "./src/assets/cardsImages/shirt2.png",
      manyLines: 1,
      manyColumns: 4,
      bgPositionX: 0,
      bgPositionY: 0,
      styles: {
        borderRadius: "0.5vw",
        padding: "0",
      },
      shopStyles: {
        borderRadius: "0.5vw",
        padding: "0",
        // backgroundSize: 'contain'
        backgroundSize: "cover",
        backgroundPosition: "center",
      },
    },
  },
  {
    id: shop_shirts_items_ids.shirtClassic3Id,
    name: "Классическая рубашка",
    type: "backs",
    bgType: "images",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "classic-back",
    description: "Классическая рубашка",
    rarity: "common",
    unlockCondition: null,
    // previewImage: "assets/shop/previews/blue_back.png",
    previewImage: {
      spriteSheet: false,
      img: "./src/assets/cardsImages/shirt3.png",
      manyLines: 1,
      manyColumns: 4,
      bgPositionX: 0,
      bgPositionY: 0,
      styles: {
        borderRadius: "0.5vw",
        padding: "0",
      },
      shopStyles: {
        borderRadius: "0.5vw",
        padding: "0",
        // backgroundSize: "contain",
        backgroundSize: "cover",
        backgroundPosition: "center",
      },
    },
  },
  {
    id: shop_shirts_items_ids.shirtClassic4Id,
    name: "Классическая рубашка",
    type: "backs",
    bgType: "images",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "classic-back",
    description: "Классическая рубашка",
    rarity: "common",
    unlockCondition: null,
    // previewImage: "assets/shop/previews/blue_back.png",
    previewImage: {
      spriteSheet: false,
      img: "./src/assets/cardsImages/shirt4.png",
      manyLines: 1,
      manyColumns: 4,
      bgPositionX: 0,
      bgPositionY: 0,
      styles: {
        borderRadius: "0.5vw",
        padding: "0",
      },
      shopStyles: {
        borderRadius: "0.5vw",
        padding: "0",
        // backgroundSize: "contain",
        backgroundSize: "cover",
        backgroundPosition: "center",
      },
    },
  },
  {
    id: shop_shirts_items_ids.shirtClassic5Id,
    name: "Классическая рубашка",
    type: "backs",
    bgType: "images",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "classic-back",
    description: "Классическая рубашка",
    rarity: "common",
    unlockCondition: null,
    previewImage: {
      spriteSheet: false,
      img: "./src/assets/cardsImages/shirt6.png",
      manyLines: 1,
      manyColumns: 4,
      bgPositionX: 0,
      bgPositionY: 0,
      styles: {
        borderRadius: "0.5vw",
        padding: "0",
      },
      shopStyles: {
        borderRadius: "0.5vw",
        padding: "0",
        backgroundSize: "cover",
        backgroundPosition: "center",
      },
    },
  },
  {
    id: shop_shirts_items_ids.shirtClassic6Id,
    name: "Классическая рубашка",
    type: "backs",
    bgType: "styles",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "classic-back",
    description: "Классическая рубашка",
    rarity: "common",
    unlockCondition: null,
    previewImage: "assets/shop/previews/blue_back.png",
    styles: {
      background:
        "repeating-linear-gradient(45deg,#1a5a1a,#1a5a1a 10px,#165016 10px,#165016 20px)",
      color: "transparent !important",
    },
  },
  {
    id: shop_shirts_items_ids.shirtClassic7Id,
    name: "Игральные кости",
    type: "backs",
    bgType: "styles",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "dice-back",
    description: "Много игральных костей",
    rarity: "common",
    unlockCondition: null,
    previewImage: "assets/shop/previews/blue_back.png",
    styles: {
      backgroundColor: "#fff",
      backgroundImage: ` radial-gradient(#000 20%, transparent 20%), radial-gradient(#000 20%, transparent 20%)`,
      backgroundSize: "20px 20px",
      backgroundPosition: "0 0, 10px 10px",
    },
  },
  {
    id: shop_shirts_items_ids.shirtClassic8Id,
    name: "Золотая рубашка",
    type: "backs",
    bgType: "styles",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "goldV-back",
    description: "Золотая рубашка",
    rarity: "common",
    unlockCondition: null,
    previewImage: "assets/shop/previews/blue_back.png",
    styles: {
      backgroundColor: "#d4af37",
      backgroundImage: `radial-gradient(circle at 10% 20%, rgba(255, 255, 255, 0.3) 0%, transparent 20%),
          radial-gradient(circle at 90% 80%, rgba(255, 255, 255, 0.3) 0%, transparent 20%)`,
    },
  },
  {
    id: shop_shirts_items_ids.shirtClassic9Id,
    name: "Деревянный стиль",
    type: "backs",
    bgType: "styles",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "treeB-back",
    description: "Деревянный стиль рубашек",
    rarity: "common",
    unlockCondition: null,
    previewImage: "assets/shop/previews/blue_back.png",
    styles: {
      backgroundColor: "#8b4513",
      backgroundImage: `linear-gradient(to right, rgba(0, 0, 0, 0.1) 0px,rgba(0, 0, 0, 0.1) 1px, transparent 1px, transparent 100%),
          linear-gradient(to bottom, rgba(0, 0, 0, 0.1) 0px,rgba(0, 0, 0, 0.1) 1px,transparent 1px,transparent 100%)`,
      backgroundSize: "10px 10px",
    },
  },
  {
    id: shop_shirts_items_ids.shirtClassic10Id,
    name: "Элегантно-красный стиль",
    type: "backs",
    bgType: "styles",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "elegantRed-back",
    description: "Элегантно-красный стиль",
    rarity: "common",
    unlockCondition: null,
    previewImage: "assets/shop/previews/blue_back.png",
    styles: {
      background: `repeating-linear-gradient(45deg,#8b0000,#8b0000 10px,#6b0000 10px,#6b0000 20px)`,
      boxShadow: "inset 0 0 10px rgba(0, 0, 0, 0.5)",
    },
  },
  {
    id: shop_shirts_items_ids.shirtClassic11Id,
    name: "Элегантно-синий стиль",
    type: "backs",
    bgType: "styles",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "elegantBlue-back",
    description: "Элегантно-синий стиль",
    rarity: "common",
    unlockCondition: null,
    previewImage: "assets/shop/previews/blue_back.png",
    styles: {
      background: `repeating-linear-gradient(45deg,#00008b,#00008b 10px,#00006b 10px,#00006b 20px)`,
      boxShadow: "inset 0 0 10px rgba(58, 8, 236, 0.5)",
    },
  },
];

export const shop_fons_items = [
  {
    id: shop_fons_items_ids.fonGreenClassicId,
    name: "Классический зелёный",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "classic-fon",
    description: "Классический фон",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "",
    styles: {
      backgroundColor: "green",
      // width: "226px",
      // height: "170px",
    },
  },
  {
    id: shop_fons_items_ids.fonGreenClassicImgId,
    name: "Классический зелёный",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "green-classic-fon-img",
    description: "Классический фон",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "./src/assets/shop/fons/fonG1.png",
    styles: "",
  },
  {
    id: shop_fons_items_ids.fonClassicId,
    name: "Классический зелёный",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "classic-fon2",
    description: "Классический фон",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "./src/assets/shop/fons/fonG2_226.png",
    styles: "",
  },
  {
    id: shop_fons_items_ids.fonRedTreeId,
    name: "Красное дерево",
    type: "backgrounds",
    bgType: "image",
    category: "background",
    owned: false,
    isBought: false,
    price: 100,
    styleClass: "red-tree-fon",
    description: "Красное дерево",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "./src/assets/shop/fons/fonG3_226.png",
    styles: "",
  },
  {
    id: shop_fons_items_ids.fonIceId,
    name: "Красное дерево",
    type: "backgrounds",
    bgType: "image",
    category: "background",
    owned: false,
    isBought: false,
    price: 100,
    styleClass: "ice-fon",
    description: "Красное дерево",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "./src/assets/shop/fons/fonG4_226.png",
    styles: "",
  },
  {
    id: shop_fons_items_ids.fonSeaId,
    name: "Красное дерево",
    type: "backgrounds",
    bgType: "image",
    category: "background",
    owned: false,
    isBought: false,
    price: 100,
    styleClass: "sea-fon",
    description: "Красное дерево",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "./src/assets/shop/fons/seaG1.png",
    styles: "",
  },
  {
    id: shop_fons_items_ids.fonAquarium2Id,
    name: "Красное дерево",
    type: "backgrounds",
    bgType: "image",
    category: "background",
    owned: false,
    isBought: false,
    price: 100,
    styleClass: "aquarium2-fon",
    description: "Красное дерево",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "./src/assets/shop/fons/aquariumG2.png",
    styles: "",
  },
  {
    id: shop_fons_items_ids.fonNature1Id,
    name: "Красное дерево",
    type: "backgrounds",
    bgType: "image",
    category: "background",
    owned: false,
    isBought: false,
    price: 100,
    styleClass: "nature1-fon",
    description: "Красное дерево",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "./src/assets/shop/fons/natureG1.png",
    styles: "",
  },
  {
    id: shop_fons_items_ids.fonLightGreenId,
    name: "Классический светло-зелёный",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "light-green-fon",
    description: "Классический светло-зелёный",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "",
    styles: {
      backgroundColor: "rgb(104, 189, 104)",
      // width: "226px",
      // height: "170px",
    },
  },
  {
    id: shop_fons_items_ids.fonClassic2Id,
    name: "Классический 2",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "classic-fon-2",
    description: "Классический 2",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "",
    styles: {
      // width: "226px",
      // height: "170px",
      background: `linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab)`,
      backgroundSize: "400% 400%",
      animation: "gradientBG 15s ease infinite",
    },
  },
  {
    id: shop_fons_items_ids.fonClassic3Id,
    name: "Классический 3",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "classic-fon-3",
    description: "Классический 3",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "",
    styles: {
      // width: "226px",
      // height: "170px",
      background: `linear-gradient(#2b2b44 2px, transparent 2px),
    linear-gradient(90deg, #2b2b44 2px, transparent 2px),
    linear-gradient(#3b3b5a 1px, transparent 1px),
    linear-gradient(90deg, #3b3b5a 1px, #1a1a2e 1px)`,
      backgroundSize: "50px 50px, 50px 50px, 10px 10px, 10px 10px",
      backgroundPosition: "-2px -2px, -2px -2px, -1px -1px, -1px -1px",
    },
  },
  {
    id: shop_fons_items_ids.fonClassic4Id,
    name: "Классический 4",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "classic-fon-4",
    description: "Классический 4",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "",
    styles: {
      // width: "226px",
      // height: "170px",
      background: `radial-gradient(circle, transparent 20%, #1a1a1a 20%, #1a1a1a 80%, transparent 80%, transparent),
    radial-gradient(circle, transparent 20%, #1a1a1a 20%, #1a1a1a 80%, transparent 80%, transparent) 50px 50px,
    linear-gradient(#2d2d2d 2px, transparent 2px) 0 -1px,
    linear-gradient(90deg, #2d2d2d 2px, #1a1a1a 2px) -1px 0`,
      backgroundSize: "100px 100px, 100px 100px, 50px 50px, 50px 50px",
      backgroundColor: "#1a1a1a",
    },
  },
  {
    id: shop_fons_items_ids.fonClassic5Id,
    name: "Классический 5",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "classic-fon-5",
    description: "Классический 5",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "",
    styles: {
      // width: "226px",
      // height: "170px",
      background: `linear-gradient(135deg, 
      rgba(100,149,237,0.1) 0%, 
      rgba(100,149,237,0) 50%, 
      rgba(100,149,237,0.1) 100%
    ),
    linear-gradient(45deg, 
      rgba(255,255,255,0.05) 1px, 
      transparent 1px
    ),
    linear-gradient(-45deg, 
      rgba(255,255,255,0.05) 1px, 
      transparent 1px
    )`,
      backgroundSize: "100% 100%, 30px 30px, 30px 30px",
      backgroundColor: "#0a1a2f",
    },
  },
  {
    id: shop_fons_items_ids.fonClassic6Id,
    name: "Классический 6",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "classic-fon-6",
    description: "Классический 6",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "",
    styles: {
      // width: "226px",
      // height: "170px",
      backgroundColor: "#52411b",
      backgroundImage: `linear-gradient(to bottom, 
          rgba(0, 0, 0, 0.589) 0%,
      transparent 80%
    ),
    url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100"><path fill="none" stroke="rgba(0,0,0,0.05)" stroke-width="2.5" d="M0,0 L100,0 L100,100 L0,100 Z M10,10 C40,10 60,40 90,40 M10,60 C40,60 60,30 90,30"/></svg>')`,
      backgroundSize: "100% 100%, 100px 100px",
    },
  },
  {
    id: shop_fons_items_ids.fonClassic7Id,
    name: "Классический 7",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 5,
    styleClass: "classic-fon-7",
    description: "Классический 7",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "",
    styles: {
      //  width: "226px",
      // height: "170px",
      background: `conic-gradient(from 90deg at 1px 1px, 
        transparent 25%, 
        #8a2be2 0%, 
        #8a2be2 50%, 
        transparent 0%, 
        transparent 75%, 
        #4b0082 0%
        )`,
      backgroundColor: " #1e0036",
      backgroundSize: "25px 25px",
    },
  },
];

console.log({ ...shop_faces_items });

export const shop_items = {
  [SHOP_CATEGORY.FACES]: [...shop_faces_items],
  [SHOP_CATEGORY.SHIRTS]: [...shop_shirts_items],
  [SHOP_CATEGORY.FONS]: [...shop_fons_items],
};

export const SHOP_DEFAULT_ITEMS = {
  faces: {
    id: "start_classic_faces",
    name: "Классические2",
    type: "faces",
    bgType: "images",
    category: "cardFace",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "start-classic-faces",
    description: "Стандартный дизайн карт",
    rarity: "common",
    unlockCondition: null,
    previewImage: {
      spriteSheet: true,
      img: "./src/assets/cardsImages/classic_cards_mini.png",
      joker: "./src/assets/cardsImages/classic_cards_joker_mini.png",
      manyLines: 4,
      manyColumns: 13,
      styles: {
        borderRadius: "0.5vw",
        padding: "0",
      },
      shopStyles: {
        borderRadius: "0.5vw",
        padding: "0",
      },
    },
  },
  backs: {
    id: "start_classic_back_img",
    name: "Классическая рубашка",
    type: "backs",
    bgType: "images",
    category: "cardBack",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "start-classic-back-img",
    description: "Классическая рубашка",
    rarity: "common",
    unlockCondition: null,
    previewImage: {
      spriteSheet: false,
      img: "./src/assets/cardsImages/shirt1.png",
      manyLines: 1,
      manyColumns: 4,
      bgPositionX: 0,
      bgPositionY: 0,
      styles: {
        borderRadius: "1.5vw",
        padding: "0",
      },
      shopStyles: {
        borderRadius: "1.5vw",
        padding: "0",
        // backgroundSize: "contain",
        backgroundSize: "cover",
        backgroundPosition: "center",
      },
    },
  },
  backgrounds: {
    id: "green_classic_fon_img",
    name: "Классический зелёный",
    type: "backgrounds",
    bgType: "styles",
    category: "background",
    owned: false,
    isBought: false,
    price: 0,
    styleClass: "green-classic-fon-img",
    description: "Классический фон",
    rarity: "rare",
    unlockCondition: { score: 1000 },
    previewImage: "./src/assets/shop/fons/fonG1.png",
    styles: "",
  },
};

export const ShopConfig = {
  categories: {
    cardFaces: {
      id: "cardFaces",
      name: "Лица карт",
      icon: "♠️",
      enabled: true,
    },
    cardBacks: {
      id: "cardBacks",
      name: "Рубашки",
      icon: "🃏",
      enabled: true,
    },
    backgrounds: {
      id: "backgrounds",
      name: "Фоны",
      icon: "🎨",
      enabled: true,
    },
    specialEffects: {
      id: "specialEffects",
      name: "Эффекты",
      icon: "✨",
      enabled: false, // Будет добавлено в будущем
    },
  },

  //   items: [
  //     // === Лица карт ===
  //     SHOP_DEFAULT_ITEMS.faces,
  //     {
  //       id: shop_items_ids.FACES.oldClassicId,
  //       name: "Классические2",
  //       type: "faces",
  //       bgType: "images",
  //       category: "cardFace",
  //       owned: false,
  //       isBought: false,
  //       price: 100,
  //       styleClass: "old-classic-faces",
  //       description: "Стандартный дизайн карт",
  //       rarity: "common",
  //       unlockCondition: null,
  //       previewImage: {
  //         spriteSheet: true,
  //         img: "./src/assets/cardsImages/old_cards_2_mini.png",
  //         joker: "./src/assets/cardsImages/old_cards_2_joker_mini.png",
  //         manyLines: 4,
  //         manyColumns: 13,
  //         styles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //         },
  //         shopStyles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //         },
  //       },
  //     },

  //     // === Рубашки карт ===
  //     SHOP_DEFAULT_ITEMS.backs,
  //     {
  //       id: shop_items_ids.BACKS.classic2Id,
  //       name: "Классическая рубашка",
  //       type: "backs",
  //       bgType: "images",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 0,
  //       styleClass: "classic-back",
  //       description: "Классическая рубашка",
  //       rarity: "common",
  //       unlockCondition: null,
  //       // previewImage: "assets/shop/previews/blue_back.png",
  //       previewImage: {
  //         spriteSheet: false,
  //         img: "./src/assets/cardsImages/shirt2.png",
  //         manyLines: 1,
  //         manyColumns: 4,
  //         bgPositionX: 0,
  //         bgPositionY: 0,
  //         styles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //         },
  //         shopStyles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //           // backgroundSize: 'contain'
  //           backgroundSize: "cover",
  //           backgroundPosition: "center",
  //         },
  //       },
  //     },
  //     {
  //       id: shop_items_ids.BACKS.classic3Id,
  //       name: "Классическая рубашка",
  //       type: "backs",
  //       bgType: "images",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 0,
  //       styleClass: "classic-back",
  //       description: "Классическая рубашка",
  //       rarity: "common",
  //       unlockCondition: null,
  //       // previewImage: "assets/shop/previews/blue_back.png",
  //       previewImage: {
  //         spriteSheet: false,
  //         img: "./src/assets/cardsImages/shirt3.png",
  //         manyLines: 1,
  //         manyColumns: 4,
  //         bgPositionX: 0,
  //         bgPositionY: 0,
  //         styles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //         },
  //         shopStyles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //           // backgroundSize: "contain",
  //           backgroundSize: "cover",
  //           backgroundPosition: "center",
  //         },
  //       },
  //     },
  //     {
  //       id: shop_items_ids.BACKS.classic4Id,
  //       name: "Классическая рубашка",
  //       type: "backs",
  //       bgType: "images",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 0,
  //       styleClass: "classic-back",
  //       description: "Классическая рубашка",
  //       rarity: "common",
  //       unlockCondition: null,
  //       // previewImage: "assets/shop/previews/blue_back.png",
  //       previewImage: {
  //         spriteSheet: false,
  //         img: "./src/assets/cardsImages/shirt4.png",
  //         manyLines: 1,
  //         manyColumns: 4,
  //         bgPositionX: 0,
  //         bgPositionY: 0,
  //         styles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //         },
  //         shopStyles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //           // backgroundSize: "contain",
  //           backgroundSize: "cover",
  //           backgroundPosition: "center",
  //         },
  //       },
  //     },
  //     {
  //       id: shop_items_ids.BACKS.classic5Id,
  //       name: "Классическая рубашка",
  //       type: "backs",
  //       bgType: "images",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 0,
  //       styleClass: "classic-back",
  //       description: "Классическая рубашка",
  //       rarity: "common",
  //       unlockCondition: null,
  //       previewImage: {
  //         spriteSheet: false,
  //         img: "./src/assets/cardsImages/shirt6.png",
  //         manyLines: 1,
  //         manyColumns: 4,
  //         bgPositionX: 0,
  //         bgPositionY: 0,
  //         styles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //         },
  //         shopStyles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //           backgroundSize: "cover",
  //           backgroundPosition: "center",
  //         },
  //       },
  //     },
  //     {
  //       id: "joker1",
  //       name: "Классическая рубашка",
  //       type: "backs",
  //       bgType: "images",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 0,
  //       styleClass: "classic-back",
  //       description: "Классическая рубашка",
  //       rarity: "common",
  //       unlockCondition: null,
  //       previewImage: {
  //         spriteSheet: false,
  //         img: "./src/assets/cardsImages/joker2.png",
  //         manyLines: 1,
  //         manyColumns: 4,
  //         bgPositionX: 0,
  //         bgPositionY: 0,
  //         styles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //         },
  //         shopStyles: {
  //           borderRadius: "0.5vw",
  //           padding: "0",
  //           backgroundSize: "cover",
  //           backgroundPosition: "center",
  //         },
  //       },
  //     },
  //     //////////////////////////////////////////
  //     {
  //       id: shop_items_ids.BACKS.classic6Id,
  //       name: "Классическая рубашка",
  //       type: "backs",
  //       bgType: "styles",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 0,
  //       styleClass: "classic-back",
  //       description: "Классическая рубашка",
  //       rarity: "common",
  //       unlockCondition: null,
  //       previewImage: "assets/shop/previews/blue_back.png",
  //       styles: {
  //         background:
  //           "repeating-linear-gradient(45deg,#1a5a1a,#1a5a1a 10px,#165016 10px,#165016 20px)",
  //         color: "transparent !important",
  //       },
  //     },
  //     {
  //       id: shop_items_ids.BACKS.classic7Id,
  //       name: "Игральные кости",
  //       type: "backs",
  //       bgType: "styles",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "dice-back",
  //       description: "Много игральных костей",
  //       rarity: "common",
  //       unlockCondition: null,
  //       previewImage: "assets/shop/previews/blue_back.png",
  //       styles: {
  //         backgroundColor: "#fff",
  //         backgroundImage: ` radial-gradient(#000 20%, transparent 20%), radial-gradient(#000 20%, transparent 20%)`,
  //         backgroundSize: "20px 20px",
  //         backgroundPosition: "0 0, 10px 10px",
  //       },
  //     },
  //     {
  //       id: shop_items_ids.BACKS.classic8Id,
  //       name: "Золотая рубашка",
  //       type: "backs",
  //       bgType: "styles",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "goldV-back",
  //       description: "Золотая рубашка",
  //       rarity: "common",
  //       unlockCondition: null,
  //       previewImage: "assets/shop/previews/blue_back.png",
  //       styles: {
  //         backgroundColor: "#d4af37",
  //         backgroundImage: `radial-gradient(circle at 10% 20%, rgba(255, 255, 255, 0.3) 0%, transparent 20%),
  //           radial-gradient(circle at 90% 80%, rgba(255, 255, 255, 0.3) 0%, transparent 20%)`,
  //       },
  //     },
  //     {
  //       id: shop_items_ids.BACKS.classic9Id,
  //       name: "Деревянный стиль",
  //       type: "backs",
  //       bgType: "styles",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "treeB-back",
  //       description: "Деревянный стиль рубашек",
  //       rarity: "common",
  //       unlockCondition: null,
  //       previewImage: "assets/shop/previews/blue_back.png",
  //       styles: {
  //         backgroundColor: "#8b4513",
  //         backgroundImage: `linear-gradient(to right, rgba(0, 0, 0, 0.1) 0px,rgba(0, 0, 0, 0.1) 1px, transparent 1px, transparent 100%),
  //           linear-gradient(to bottom, rgba(0, 0, 0, 0.1) 0px,rgba(0, 0, 0, 0.1) 1px,transparent 1px,transparent 100%)`,
  //         backgroundSize: "10px 10px",
  //       },
  //     },
  //     {
  //       id: shop_items_ids.BACKS.classic10Id,
  //       name: "Элегантно-красный стиль",
  //       type: "backs",
  //       bgType: "styles",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "elegantRed-back",
  //       description: "Элегантно-красный стиль",
  //       rarity: "common",
  //       unlockCondition: null,
  //       previewImage: "assets/shop/previews/blue_back.png",
  //       styles: {
  //         background: `repeating-linear-gradient(45deg,#8b0000,#8b0000 10px,#6b0000 10px,#6b0000 20px)`,
  //         boxShadow: "inset 0 0 10px rgba(0, 0, 0, 0.5)",
  //       },
  //     },
  //     {
  //       id: shop_items_ids.BACKS.classic11Id,
  //       name: "Элегантно-синий стиль",
  //       type: "backs",
  //       bgType: "styles",
  //       category: "cardBack",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "elegantBlue-back",
  //       description: "Элегантно-синий стиль",
  //       rarity: "common",
  //       unlockCondition: null,
  //       previewImage: "assets/shop/previews/blue_back.png",
  //       styles: {
  //         background: `repeating-linear-gradient(45deg,#00008b,#00008b 10px,#00006b 10px,#00006b 20px)`,
  //         boxShadow: "inset 0 0 10px rgba(58, 8, 236, 0.5)",
  //       },
  //     },

  //     // === Фоны ===
  //     {
  //       id: shop_items_ids.FONS.greenClassicId,
  //       name: "Классический зелёный",
  //       type: "backgrounds",
  //       bgType: "styles",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 0,
  //       styleClass: "classic-fon",
  //       description: "Классический фон",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "",
  //       styles: {
  //         backgroundColor: "green",
  //         // width: "226px",
  //         // height: "170px",
  //       },
  //     },
  //     ///////////////////////////
  //     SHOP_DEFAULT_ITEMS.backgrounds,
  //     {
  //       id: shop_items_ids.FONS.classicId,
  //       name: "Классический зелёный",
  //       type: "backgrounds",
  //       bgType: "styles",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 0,
  //       styleClass: "classic-fon2",
  //       description: "Классический фон",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "./src/assets/shop/fons/fonG2_226.png",
  //       styles: "",
  //     },
  //     {
  //       id: shop_items_ids.FONS.redTreeId,
  //       name: "Красное дерево",
  //       type: "backgrounds",
  //       bgType: "image",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 100,
  //       styleClass: "red-tree-fon",
  //       description: "Красное дерево",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "./src/assets/shop/fons/fonG3_226.png",
  //       styles: "",
  //     },
  //     {
  //       id: shop_items_ids.FONS.iceId,
  //       name: "Красное дерево",
  //       type: "backgrounds",
  //       bgType: "image",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 100,
  //       styleClass: "ice-fon",
  //       description: "Красное дерево",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "./src/assets/shop/fons/fonG4_226.png",
  //       styles: "",
  //     },
  //     {
  //       id: shop_items_ids.FONS.seaId,
  //       name: "Красное дерево",
  //       type: "backgrounds",
  //       bgType: "image",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 100,
  //       styleClass: "sea-fon",
  //       description: "Красное дерево",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "./src/assets/shop/fons/seaG1.png",
  //       styles: "",
  //     },
  //     {
  //       id: shop_items_ids.FONS.aquarium2Id,
  //       name: "Красное дерево",
  //       type: "backgrounds",
  //       bgType: "image",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 100,
  //       styleClass: "aquarium2-fon",
  //       description: "Красное дерево",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "./src/assets/shop/fons/aquariumG2.png",
  //       styles: "",
  //     },
  //     {
  //       id: shop_items_ids.FONS.nature1Id,
  //       name: "Красное дерево",
  //       type: "backgrounds",
  //       bgType: "image",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 100,
  //       styleClass: "nature1-fon",
  //       description: "Красное дерево",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "./src/assets/shop/fons/natureG1.png",
  //       styles: "",
  //     },
  //     /////////////////////////
  //     {
  //       id: shop_items_ids.FONS.lightGreenId,
  //       name: "Классический светло-зелёный",
  //       type: "backgrounds",
  //       bgType: "styles",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 0,
  //       styleClass: "light-green-fon",
  //       description: "Классический светло-зелёный",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "",
  //       styles: {
  //         backgroundColor: "rgb(104, 189, 104)",
  //         // width: "226px",
  //         // height: "170px",
  //       },
  //     },
  //     {
  //       id: shop_items_ids.FONS.classic2Id,
  //       name: "Классический 2",
  //       type: "backgrounds",
  //       bgType: "styles",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "classic-fon-2",
  //       description: "Классический 2",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "",
  //       styles: {
  //         // width: "226px",
  //         // height: "170px",
  //         background: `linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab)`,
  //         backgroundSize: "400% 400%",
  //         animation: "gradientBG 15s ease infinite",
  //       },
  //     },
  //     {
  //       id: shop_items_ids.FONS.classic3Id,
  //       name: "Классический 3",
  //       type: "backgrounds",
  //       bgType: "styles",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "classic-fon-3",
  //       description: "Классический 3",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "",
  //       styles: {
  //         // width: "226px",
  //         // height: "170px",
  //         background: `linear-gradient(#2b2b44 2px, transparent 2px),
  //     linear-gradient(90deg, #2b2b44 2px, transparent 2px),
  //     linear-gradient(#3b3b5a 1px, transparent 1px),
  //     linear-gradient(90deg, #3b3b5a 1px, #1a1a2e 1px)`,
  //         backgroundSize: "50px 50px, 50px 50px, 10px 10px, 10px 10px",
  //         backgroundPosition: "-2px -2px, -2px -2px, -1px -1px, -1px -1px",
  //       },
  //     },
  //     {
  //       id: shop_items_ids.FONS.classic4Id,
  //       name: "Классический 4",
  //       type: "backgrounds",
  //       bgType: "styles",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "classic-fon-4",
  //       description: "Классический 4",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "",
  //       styles: {
  //         // width: "226px",
  //         // height: "170px",
  //         background: `radial-gradient(circle, transparent 20%, #1a1a1a 20%, #1a1a1a 80%, transparent 80%, transparent),
  //     radial-gradient(circle, transparent 20%, #1a1a1a 20%, #1a1a1a 80%, transparent 80%, transparent) 50px 50px,
  //     linear-gradient(#2d2d2d 2px, transparent 2px) 0 -1px,
  //     linear-gradient(90deg, #2d2d2d 2px, #1a1a1a 2px) -1px 0`,
  //         backgroundSize: "100px 100px, 100px 100px, 50px 50px, 50px 50px",
  //         backgroundColor: "#1a1a1a",
  //       },
  //     },
  //     {
  //       id: shop_items_ids.FONS.classic5Id,
  //       name: "Классический 5",
  //       type: "backgrounds",
  //       bgType: "styles",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "classic-fon-5",
  //       description: "Классический 5",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "",
  //       styles: {
  //         // width: "226px",
  //         // height: "170px",
  //         background: `linear-gradient(135deg,
  //       rgba(100,149,237,0.1) 0%,
  //       rgba(100,149,237,0) 50%,
  //       rgba(100,149,237,0.1) 100%
  //     ),
  //     linear-gradient(45deg,
  //       rgba(255,255,255,0.05) 1px,
  //       transparent 1px
  //     ),
  //     linear-gradient(-45deg,
  //       rgba(255,255,255,0.05) 1px,
  //       transparent 1px
  //     )`,
  //         backgroundSize: "100% 100%, 30px 30px, 30px 30px",
  //         backgroundColor: "#0a1a2f",
  //       },
  //     },
  //     {
  //       id: shop_items_ids.FONS.classic6Id,
  //       name: "Классический 6",
  //       type: "backgrounds",
  //       bgType: "styles",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "classic-fon-6",
  //       description: "Классический 6",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "",
  //       styles: {
  //         // width: "226px",
  //         // height: "170px",
  //         backgroundColor: "#52411b",
  //         backgroundImage: `linear-gradient(to bottom,
  //           rgba(0, 0, 0, 0.589) 0%,
  //       transparent 80%
  //     ),
  //     url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100"><path fill="none" stroke="rgba(0,0,0,0.05)" stroke-width="2.5" d="M0,0 L100,0 L100,100 L0,100 Z M10,10 C40,10 60,40 90,40 M10,60 C40,60 60,30 90,30"/></svg>')`,
  //         backgroundSize: "100% 100%, 100px 100px",
  //       },
  //     },
  //     {
  //       id: shop_items_ids.FONS.classic7Id,
  //       name: "Классический 7",
  //       type: "backgrounds",
  //       bgType: "styles",
  //       category: "background",
  //       owned: false,
  //       isBought: false,
  //       price: 5,
  //       styleClass: "classic-fon-7",
  //       description: "Классический 7",
  //       rarity: "rare",
  //       unlockCondition: { score: 1000 },
  //       previewImage: "",
  //       styles: {
  //         //  width: "226px",
  //         // height: "170px",
  //         background: `conic-gradient(from 90deg at 1px 1px,
  //         transparent 25%,
  //         #8a2be2 0%,
  //         #8a2be2 50%,
  //         transparent 0%,
  //         transparent 75%,
  //         #4b0082 0%
  //         )`,
  //         backgroundColor: " #1e0036",
  //         backgroundSize: "25px 25px",
  //       },
  //     },
  //   ],

  currencies: {
    coins: {
      name: "Монеты",
      icon: "🪙",
      exchangeRate: 1,
    },
    gems: {
      name: "Кристаллы",
      icon: "💎",
      exchangeRate: 100,
      premium: true,
    },
  },

  rarities: {
    common: {
      name: "Обычный",
      color: "#a0a0a0",
    },
    uncommon: {
      name: "Необычный",
      color: "#2ecc71",
    },
    rare: {
      name: "Редкий",
      color: "#3498db",
    },
    epic: {
      name: "Эпический",
      color: "#9b59b6",
    },
    legendary: {
      name: "Легендарный",
      color: "#f1c40f",
    },
  },

  defaultShopState: {
    currentCategory: "faces",
    purchasedItems: [],
    selectedItems: {
      cardFace: "classic_faces",
      cardBack: "blue_back",
      background: "green_felt",
    },
  },

  defaultItems: {
    cardFace: "classic_faces",
    cardBack: "blue_back",
    background: "default_bg",
  },
};
